name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: cd frontend && yarn install

    - name: Add missing dependencies
      run: cd frontend && yarn add chart.js && yarn add --dev @babel/plugin-proposal-private-property-in-object

    - name: Add TypeScript
      run: cd frontend && yarn add typescript

    - name: Build
      run: cd frontend && yarn run build

    - name: Run linter
      run: cd frontend && yarn run lint
